. $WERCKER_STEP_ROOT/setup.sh

echo "Going to set env..."

export WERCKER_ANDROID_GOOGLEPLAY_SERVICE_ACCOUNT_KEY_FILE_PATH="${WERCKER_STEP_ROOT}/key.p12"
echo "${WERCKER_ANDROID_GOOGLEPLAY_SERVICE_ACCOUNT_KEY_BASE64}" | base64 -d > "$WERCKER_ANDROID_GOOGLEPLAY_SERVICE_ACCOUNT_KEY_FILE_PATH"

export WERCKER_ANDROID_GOOGLEPLAY_APK_FILE_PATH="${WERCKER_ROOT}/${WERCKER_ANDROID_GOOGLEPLAY_APK_FILE_PATH}"

cd "$WERCKER_STEP_ROOT"
sbt run
