. $WERCKER_STEP_ROOT/setup.sh

export WERCKER_ANDROID_GOOGLEPLAY_SERVICE_ACCOUNT_KEY_FILE_PATH="${WERCKER_STEP_ROOT}/key.p12"
echo "${WERCKER_ANDROID_GOOGLEPLAY_SERVICE_ACCOUNT_KEY_BASE64}" | base64 -d > "$WERCKER_ANDROID_GOOGLEPLAY_SERVICE_ACCOUNT_KEY_FILE_PATH"

export WERCKER_ANDROID_GOOGLEPLAY_APK_FILE_PATH="${WERCKER_OUTPUT_DIR}/${WERCKER_ANDROID_GOOGLEPLAY_APK_FILE_PATH}"

pwd
ls -la "$WERCKER_OUTPUT_DIR"

echo "Uploading $WERCKER_ANDROID_GOOGLEPLAY_APK_FILE_PATH"
[ -f "$WERCKER_ANDROID_GOOGLEPLAY_APK_FILE_PATH" ] || exit 1

cd "$WERCKER_STEP_ROOT"
sbt run
